# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlashyTable' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlashyTable
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'APParallaxHeader'
    pod 'ChameleonFramework'
end
